apiVersion: v1
kind: Namespace
metadata:
  name: 'terminal'
  labels:
    mysql: access
    m2-elastic: access
    graylog: access
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 'terminal'
  name: 'terminal'
  namespace: 'terminal'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'terminal'
  template:
    metadata:
      labels:
        app: 'terminal'
    spec:
      containers:
        -
          image: 'amila/xterm:latest'
          imagePullPolicy: Always
          name: 'terminal'
          ports:
            - containerPort: 22
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: 'terminal'
  namespace: 'terminal'
  labels:
    app: 'terminal'
spec:
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  selector:
    app: 'terminal'
  type: ClusterIP
